version: 0.0
os: windows
files:
  - source: BuildArtifacts\_PublishedWebsites\HelloWorld\*.*
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900